"""Alembic migrations: env.py, the revisions, offline SQL (F §3.1-§3.3; slice 1 spec)."""
import io
import logging.config
from contextlib import contextmanager
from pathlib import Path

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import CheckConstraint, Integer, create_engine, inspect
from sqlalchemy.pool import NullPool

from db import models  # noqa: F401  (registers every table on Base.metadata)
from db.engine import Base
from db.schema_check import ALEMBIC_INI, alembic_config, schema_diff


def _alembic(url: str, *args, **kw):
    """Run one Alembic command in-process on `url`; never reads DATABASE_URL, never touches logging."""
    return getattr(command, args[0])(alembic_config(url=url, configure_logger=False), *args[1:], **kw)


@pytest.fixture
def sqlite_url(tmp_path):
    return f"sqlite:///{tmp_path / 'migrations.db'}"


# --- env.py -------------------------------------------------------------------

@pytest.mark.parametrize("configure_logger", [True, False])
def test_env_py_configures_logging_only_when_asked(monkeypatch, sqlite_url, configure_logger):
    calls = []
    monkeypatch.setattr(logging.config, "fileConfig", lambda *a, **kw: calls.append((a, kw)))
    command.current(alembic_config(url=sqlite_url, configure_logger=configure_logger))
    expected = [((str(ALEMBIC_INI),), {"disable_existing_loggers": False})] if configure_logger else []
    assert calls == expected


def test_env_py_uses_the_configured_url_not_database_url(monkeypatch, capsys, sqlite_url, tmp_path):
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@pooler.invalid:5432/postgres")
    _alembic(sqlite_url, "current")
    err = capsys.readouterr().err
    assert "Database: dialect=sqlite" in err
    assert "pooler.invalid" not in err
    assert (tmp_path / "migrations.db").exists()


def test_env_py_prints_the_database_line_to_stderr_only(capsys, sqlite_url, tmp_path):
    _alembic(sqlite_url, "current")
    out, err = capsys.readouterr()
    assert f"Database: dialect=sqlite driver=pysqlite host=- database={tmp_path / 'migrations.db'}\n" in err
    assert "Database:" not in out


# --- 0001_baseline (Task 6) ------------------------------------------------------

BASELINE_TABLES = {
    "users", "churches", "memberships", "invites", "hymn_catalog", "hymns",
    "services", "hymn_usage", "contacts", "gmail_tokens", "oauth_states",
}


def _script() -> ScriptDirectory:
    return ScriptDirectory.from_config(alembic_config(configure_logger=False))


@contextmanager
def _connection(url: str):
    """A short-lived connection of its own (NullPool), closed and disposed on exit."""
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            yield conn
    finally:
        engine.dispose()


def test_upgrade_head_on_empty_sqlite_matches_the_models(sqlite_url):
    _alembic(sqlite_url, "upgrade", "head")
    with _connection(sqlite_url) as conn:
        assert schema_diff(conn) == []
    _alembic(sqlite_url, "check")   # AC1: raises AutogenerateDiffsDetected on any difference


def test_downgrade_base_then_upgrade_head(sqlite_url):
    _alembic(sqlite_url, "upgrade", "head")
    _alembic(sqlite_url, "downgrade", "base")
    with _connection(sqlite_url) as conn:
        assert inspect(conn).get_table_names() == ["alembic_version"]
        assert conn.exec_driver_sql("SELECT count(*) FROM alembic_version").scalar() == 0
    _alembic(sqlite_url, "upgrade", "head")
    with _connection(sqlite_url) as conn:
        assert schema_diff(conn) == []
        versions = conn.exec_driver_sql("SELECT version_num FROM alembic_version").scalars().all()
    assert versions == [_script().get_current_head()]


def test_every_revision_defines_downgrade():
    revisions = list(_script().walk_revisions())
    assert revisions
    for rev in revisions:
        assert callable(getattr(rev.module, "downgrade", None)), rev.revision
        assert Path(rev.path).name == f"{rev.revision}.py"   # NNNN_short_slug.py, id = file name


def test_there_is_a_single_head():
    script = _script()
    assert len(script.get_heads()) == 1
    assert script.get_bases() == ["0001_baseline"]
    assert not [rev.revision for rev in script.walk_revisions()
                if rev.is_branch_point or rev.is_merge_point]


def test_baseline_creates_the_eleven_tables_with_hymn_facts_columns(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0001_baseline")
    with _connection(sqlite_url) as conn:
        insp = inspect(conn)
        assert set(insp.get_table_names()) == BASELINE_TABLES | {"alembic_version"}
        for table in ("hymns", "hymn_catalog"):
            columns = {column["name"]: column for column in insp.get_columns(table)}
            for name in ("text_year", "hymnal_count"):
                assert isinstance(columns[name]["type"], Integer), (table, name)
                assert columns[name]["nullable"] is True, (table, name)
        assert {ix["name"]: ix["column_names"] for ix in insp.get_indexes("hymns")} == {
            "ix_hymns_church_id": ["church_id"],
            "ix_hymns_church_hymnal": ["church_id", "hymnal"],
            "ix_hymns_church_number": ["church_id", "number"],
        }


def _on_delete_rules_in_the_models() -> dict:
    return {
        (table.name, tuple(fk.column_keys), fk.referred_table.name): (fk.ondelete or "").upper() or None
        for table in Base.metadata.sorted_tables
        for fk in table.foreign_key_constraints
    }


def _check_constraints_in_the_models() -> dict:
    return {
        table.name: sorted((c.name, str(c.sqltext)) for c in table.constraints
                           if isinstance(c, CheckConstraint))
        for table in Base.metadata.sorted_tables
    }


def test_baseline_keeps_on_delete_rules_and_check_constraints(sqlite_url):
    """ON DELETE rules and CHECK constraints equal the models' after `upgrade head`.

    Autogenerate never compares CHECK constraints, and whether it compares ON
    DELETE depends on the Alembic version and the dialect, so schema_diff alone
    cannot be trusted with either. Runs at head, so it keeps holding when a later
    revision rebuilds a table (0004's batch mode on SQLite)."""
    _alembic(sqlite_url, "upgrade", "head")
    expected_rules = _on_delete_rules_in_the_models()
    expected_checks = _check_constraints_in_the_models()
    assert expected_rules[("memberships", ("church_id",), "churches")] == "CASCADE"
    assert expected_rules[("services", ("created_by",), "users")] == "SET NULL"
    assert expected_checks["memberships"] == [("ck_memberships_role", "role IN ('owner','admin','member')")]
    with _connection(sqlite_url) as conn:
        insp = inspect(conn)
        rules = {
            (table, tuple(fk["constrained_columns"]), fk["referred_table"]):
                (fk["options"].get("ondelete") or "").upper() or None
            for table in Base.metadata.tables
            for fk in insp.get_foreign_keys(table)
        }
        checks = {
            table: sorted((c["name"], c["sqltext"]) for c in insp.get_check_constraints(table))
            for table in Base.metadata.tables
        }
    assert rules == expected_rules
    assert checks == expected_checks


def test_offline_sql_wraps_timeouts_in_one_transaction(capsys):
    """`upgrade --sql` on Postgres opens no connection (port 1 has no server)."""
    cfg = alembic_config(url="postgresql://u:p@localhost:1/x", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "head", sql=True)
    sql = buffer.getvalue()
    lines = [line for line in sql.splitlines() if line.strip() and not line.startswith("--")]
    assert lines[:3] == ["BEGIN;", "SET LOCAL lock_timeout = '5s';", "SET LOCAL statement_timeout = '60s';"]
    assert lines[-1] == "COMMIT;"
    assert sql.count("BEGIN;") == 1
    assert sql.count("COMMIT;") == 1
    assert "CREATE TABLE users (" in sql
    assert "Database:" not in sql
    assert "Database: dialect=postgresql driver=psycopg2 host=localhost database=x" in capsys.readouterr().err


# --- Task 7: 0002_reconcile (F §3.2 item 3; S amendment 2026-09-26; AC18) ------
import io

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.pool import NullPool

from db.schema_check import schema_diff

RECONCILE_TABLES = ("hymns", "hymn_catalog")
RECONCILE_COLUMNS = ("text_year", "hymnal_count")


def _execute_on(url: str, *statements: str) -> None:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            for statement in statements:
                conn.execute(text(statement))
    finally:
        engine.dispose()


def _legacy_database(url: str, *, without_hymn_facts: bool = False,
                     without_hymnal_index: bool = False) -> None:
    """A database the old create_all made (no alembic_version table): the 0001
    schema, minus what an older one lacked (PR #4's columns, or the index
    migrate_add_hymnal.py never created)."""
    _alembic(url, "upgrade", "0001_baseline")
    statements = ["DROP TABLE alembic_version"]
    if without_hymnal_index:
        statements.append("DROP INDEX ix_hymns_church_hymnal")
    if without_hymn_facts:
        statements += [f"ALTER TABLE {table} DROP COLUMN {column}"
                       for table in RECONCILE_TABLES for column in RECONCILE_COLUMNS]
    _execute_on(url, *statements)


def _tables_snapshot(url: str) -> dict:
    """{table: (sorted (column, type, nullable), sorted (index, columns))}."""
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            insp = inspect(conn)
            return {
                table: (
                    sorted((c["name"], str(c["type"]), c["nullable"]) for c in insp.get_columns(table)),
                    sorted((i["name"], tuple(i["column_names"])) for i in insp.get_indexes(table)),
                )
                for table in insp.get_table_names()
            }
    finally:
        engine.dispose()


def _snapshot_columns(snapshot: dict, table: str) -> set[str]:
    return {name for name, _type, _nullable in snapshot[table][0]}


def _models_diff(url: str) -> list:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            return schema_diff(conn)
    finally:
        engine.dispose()


def test_a_pre_pr4_database_stamped_at_baseline_gains_hymn_facts(sqlite_url):
    _legacy_database(sqlite_url, without_hymn_facts=True)
    before = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:
        assert not set(RECONCILE_COLUMNS) & _snapshot_columns(before, table)

    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")

    after = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:
        columns = {name: (type_, nullable) for name, type_, nullable in after[table][0]}
        assert columns["text_year"] == ("INTEGER", True)
        assert columns["hymnal_count"] == ("INTEGER", True)
    assert _models_diff(sqlite_url) == []


def test_upgrade_head_twice_changes_nothing(sqlite_url):
    _legacy_database(sqlite_url, without_hymn_facts=True, without_hymnal_index=True)
    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")
    first = _tables_snapshot(sqlite_url)

    _alembic(sqlite_url, "upgrade", "head")              # already at head: nothing runs
    assert _tables_snapshot(sqlite_url) == first

    # 0002 itself a second time, as on production, which already has everything.
    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "0002_reconcile")
    assert _tables_snapshot(sqlite_url) == first


def test_on_a_fresh_database_0002_adds_nothing(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0001_baseline")
    baseline = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:                       # 0001 already made them
        assert set(RECONCILE_COLUMNS) <= _snapshot_columns(baseline, table)
    assert ("ix_hymns_church_hymnal", ("church_id", "hymnal")) in baseline["hymns"][1]

    _alembic(sqlite_url, "upgrade", "0002_reconcile")

    assert _tables_snapshot(sqlite_url) == baseline


def test_a_stamped_database_missing_the_hymnal_index_gets_it(sqlite_url):
    _legacy_database(sqlite_url, without_hymnal_index=True)
    assert "ix_hymns_church_hymnal" not in {name for name, _cols in _tables_snapshot(sqlite_url)["hymns"][1]}

    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")

    assert ("ix_hymns_church_hymnal", ("church_id", "hymnal")) in _tables_snapshot(sqlite_url)["hymns"][1]
    assert _models_diff(sqlite_url) == []


def test_offline_sql_from_baseline_renders_guarded_adds_and_no_create_table():
    # Runbook step 5: `alembic upgrade 0001_baseline:head --sql`. Offline mode
    # never connects (port 1 on localhost would refuse anyway).
    cfg = alembic_config(url="postgresql://u:p@localhost:1/x", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "0001_baseline:head", sql=True)
    sql = buffer.getvalue()

    assert "CREATE TABLE" not in sql
    assert "CREATE INDEX IF NOT EXISTS ix_hymns_church_hymnal ON hymns (church_id, hymnal);" in sql
    for table in RECONCILE_TABLES:
        for column in RECONCILE_COLUMNS:
            assert f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} INTEGER;" in sql
    assert sql.count("ADD COLUMN IF NOT EXISTS") == 4
    assert ("UPDATE alembic_version SET version_num='0002_reconcile' "
            "WHERE alembic_version.version_num = '0001_baseline';") in sql


# --- 0003_lockdown (Task 8; F §3.2 item 4, §3.6) --------------------------------

import io  # noqa: E402
import os  # noqa: E402

from alembic.script import ScriptDirectory  # noqa: E402
from sqlalchemy import create_engine, text  # noqa: E402
from sqlalchemy.exc import DBAPIError  # noqa: E402
from sqlalchemy.pool import NullPool  # noqa: E402

from db.engine import Base, _normalize_url  # noqa: E402
from db import models  # noqa: E402,F401  (registers every table on Base.metadata)
from tests.pg_helpers import require_local_test_url, supabase_roles, throwaway_database  # noqa: E402

LOCKDOWN_REFUSAL = (
    "0003_lockdown: role {role} has no BYPASSRLS and does not own: {tables}. Enabling RLS would "
    'hide their rows from the app. See migrations/README.md "RLS precondition".'
)
LOCKDOWN_CANNOT_ENABLE = (
    "0003_lockdown: cannot enable RLS on {table} (owned by {owner}, migrating as {role}). "
    'Only the owner of a table can enable RLS on it. See migrations/README.md "RLS precondition".'
)
SUPABASE_REVOKES = (
    "REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;",
    "REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;",
    "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;",
    "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;",
)


def _lockdown_module():
    """The 0003 revision module, loaded by Alembic (its file name starts with a digit)."""
    script = ScriptDirectory.from_config(alembic_config(configure_logger=False))
    return script.get_revision("0003_lockdown").module


def _lockdown_offline_sql() -> str:
    """`alembic upgrade 0002_reconcile:0003_lockdown --sql` for Postgres; never connects."""
    cfg = alembic_config(url="postgresql://u:p@localhost:1/x", configure_logger=False)
    cfg.output_buffer = io.StringIO()
    command.upgrade(cfg, "0002_reconcile:0003_lockdown", sql=True)
    return cfg.output_buffer.getvalue()


def _pg_engine(url: str):
    return create_engine(_normalize_url(url), poolclass=NullPool)


def _rls_flags(engine) -> dict[str, bool]:
    """relrowsecurity of every table in `public`, by name."""
    with engine.connect() as conn:
        rows = conn.execute(text(
            "SELECT c.relname, c.relrowsecurity FROM pg_class c "
            "WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')"))
        return {name: flag for name, flag in rows}


def _create_foreign_owned_table(admin, owner: str) -> None:
    """As the admin: public.foreign_owned in the sandbox, owned by another role, RLS off."""
    with admin.begin() as conn:
        conn.execute(text("CREATE TABLE public.foreign_owned (id integer PRIMARY KEY)"))
        conn.execute(text(f"ALTER TABLE public.foreign_owned OWNER TO {owner}"))


@pytest.fixture
def pg_admin_url():
    url = os.environ.get("TEST_DATABASE_URL", "").strip()
    if not url:
        pytest.skip("TEST_DATABASE_URL is not set (the backend-postgres CI job sets it)")
    return require_local_test_url(url)


def test_0003_is_a_no_op_on_sqlite(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0002_reconcile")
    engine = create_engine(sqlite_url)
    try:
        snapshot = "SELECT type, name, tbl_name, sql FROM sqlite_master ORDER BY type, name"
        with engine.connect() as conn:
            before = conn.execute(text(snapshot)).all()
        _alembic(sqlite_url, "upgrade", "0003_lockdown")
        with engine.connect() as conn:
            assert conn.execute(text(snapshot)).all() == before
            assert conn.execute(text("SELECT version_num FROM alembic_version")).scalar_one() == "0003_lockdown"
        _alembic(sqlite_url, "downgrade", "0002_reconcile")
        with engine.connect() as conn:
            assert conn.execute(text(snapshot)).all() == before
            assert conn.execute(text("SELECT version_num FROM alembic_version")).scalar_one() == "0002_reconcile"
    finally:
        engine.dispose()


def test_offline_sql_for_0003_has_the_do_block_and_revokes():
    sql = _lockdown_offline_sql()
    lockdown = _lockdown_module().LOCKDOWN_SQL
    assert lockdown + ";" in sql                    # the module constant, verbatim
    assert sql.count("DO $$") == 1
    # Named paramstyle (env.py): RAISE placeholders and format() stay single %.
    assert "%%" not in sql
    assert LOCKDOWN_REFUSAL.format(role="%", tables="%") in sql
    assert LOCKDOWN_CANNOT_ENABLE.format(table="%", owner="%", role="%") in sql
    assert "EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tbl);" in sql
    for statement in SUPABASE_REVOKES:
        assert statement in sql
    assert "UPDATE alembic_version SET version_num='0003_lockdown' " \
           "WHERE alembic_version.version_num = '0002_reconcile';" in sql
    assert "CREATE TABLE" not in sql
    assert "DISABLE ROW LEVEL SECURITY" not in sql  # the downgrade's block is not in an upgrade


@pytest.mark.postgres
def test_0003_refuses_without_bypassrls_or_ownership_and_rolls_back(pg_admin_url):
    with throwaway_database(pg_admin_url) as sandbox:
        admin = _pg_engine(sandbox.admin_db_url)
        try:
            _create_foreign_owned_table(admin, sandbox.other_role)
            with pytest.raises(DBAPIError) as excinfo:
                _alembic(sandbox.role_url, "upgrade", "head")
            assert excinfo.value.orig.diag.message_primary == LOCKDOWN_REFUSAL.format(
                role=sandbox.role, tables="foreign_owned")
            # One transaction (env.py): 0001 and 0002 rolled back with 0003, so no
            # model table and no alembic_version exist, and RLS is still off.
            assert _rls_flags(admin) == {"foreign_owned": False}
        finally:
            admin.dispose()


@pytest.mark.postgres
def test_0003_refuses_a_bypassrls_role_that_does_not_own_a_table(pg_admin_url):
    with throwaway_database(pg_admin_url, role_bypassrls=True) as sandbox:
        admin = _pg_engine(sandbox.admin_db_url)
        try:
            _create_foreign_owned_table(admin, sandbox.other_role)
            with pytest.raises(DBAPIError) as excinfo:
                _alembic(sandbox.role_url, "upgrade", "head")
            assert excinfo.value.orig.diag.message_primary == LOCKDOWN_CANNOT_ENABLE.format(
                table="foreign_owned", owner=sandbox.other_role, role=sandbox.role)
            # The loop had already enabled RLS on alembic_version, churches and
            # contacts (alphabetical order); the rollback undid that too.
            assert _rls_flags(admin) == {"foreign_owned": False}
        finally:
            admin.dispose()


@pytest.mark.postgres
def test_0003_is_idempotent_after_the_manual_lockdown(pg_admin_url):
    with supabase_roles(pg_admin_url), throwaway_database(pg_admin_url, role_bypassrls=True) as sandbox:
        _alembic(sandbox.role_url, "upgrade", "0002_reconcile")
        owner = _pg_engine(sandbox.role_url)
        admin = _pg_engine(sandbox.admin_db_url)
        try:
            with owner.begin() as conn:
                # The ops lockdown of 2026-09-25 enabled RLS by hand; here on three tables.
                for table in ("churches", "invites", "users"):
                    conn.execute(text(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY"))
                # What Supabase's defaults give anon and authenticated before the REVOKEs.
                conn.execute(text("GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated"))

            _alembic(sandbox.role_url, "upgrade", "head")
            after_upgrade = _rls_flags(admin)
            assert after_upgrade == {name: True for name in [*Base.metadata.tables, "alembic_version"]}
            with admin.connect() as conn:
                for grantee in ("anon", "authenticated"):
                    assert conn.execute(text(
                        "SELECT has_table_privilege(:grantee, 'public.users', 'SELECT')"),
                        {"grantee": grantee}).scalar_one() is False

            with owner.begin() as conn:            # the DO block again: no error, no change
                conn.execute(text(_lockdown_module().LOCKDOWN_SQL))
            assert _rls_flags(admin) == after_upgrade
        finally:
            owner.dispose()
            admin.dispose()


# --- Task 9: 0004_invites_reusable (F §3.2 item 5, §3.4) -----------------------
import uuid
from datetime import datetime, timedelta, timezone

import sqlalchemy as sa
from sqlalchemy.pool import NullPool

T9_NOW = datetime(2026, 9, 26, 12, 0, tzinfo=timezone.utc)

# The invites columns before 0004, i.e. everything frozen Streamlit's ORM maps:
# its INSERTs name exactly these columns and never reusable or accepted_by.
_legacy_invites = sa.table(
    "invites",
    sa.column("id", sa.Uuid()),
    sa.column("church_id", sa.Uuid()),
    sa.column("code", sa.String()),
    sa.column("email", sa.String()),
    sa.column("role", sa.String()),
    sa.column("created_by", sa.Uuid()),
    sa.column("created_at", sa.DateTime(timezone=True)),
    sa.column("expires_at", sa.DateTime(timezone=True)),
    sa.column("revoked", sa.Boolean()),
    sa.column("accepted_at", sa.DateTime(timezone=True)),
)
_t9_users = sa.table(
    "users",
    sa.column("id", sa.Uuid()),
    sa.column("email", sa.String()),
    sa.column("created_at", sa.DateTime(timezone=True)),
)
_t9_churches = sa.table(
    "churches",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("timezone", sa.String()),
    sa.column("settings", sa.JSON()),
    sa.column("created_at", sa.DateTime(timezone=True)),
)


def _seed_owner_and_church(conn) -> tuple[uuid.UUID, uuid.UUID]:
    user_id, church_id = uuid.uuid4(), uuid.uuid4()
    conn.execute(_t9_users.insert().values(id=user_id, email="owner@example.com", created_at=T9_NOW))
    conn.execute(_t9_churches.insert().values(
        id=church_id, name="Grace Church", timezone="America/New_York", settings={}, created_at=T9_NOW))
    return user_id, church_id


def _insert_legacy_invite(conn, church_id, user_id, *, code, email=None, accepted_at=None) -> None:
    """An INSERT shaped like frozen Streamlit's: no reusable, no accepted_by."""
    conn.execute(_legacy_invites.insert().values(
        id=uuid.uuid4(), church_id=church_id, code=code, email=email, role="member",
        created_by=user_id, created_at=T9_NOW, expires_at=T9_NOW + timedelta(days=7),
        revoked=False, accepted_at=accepted_at))


def _invites_shape(conn) -> dict:
    """Everything a table recreate could lose: columns, keys, constraints, indexes."""
    insp = sa.inspect(conn)
    return {
        "columns": [(c["name"], str(c["type"]), c["nullable"]) for c in insp.get_columns("invites")],
        "pk": insp.get_pk_constraint("invites")["constrained_columns"],
        "fks": sorted(
            (fk["name"] or "", tuple(fk["constrained_columns"]), fk["referred_table"],
             tuple(fk["referred_columns"]), fk["options"].get("ondelete"))
            for fk in insp.get_foreign_keys("invites")),
        "uniques": sorted((u["name"] or "", tuple(u["column_names"]))
                          for u in insp.get_unique_constraints("invites")),
        "indexes": sorted((i["name"], tuple(i["column_names"]), bool(i["unique"]))
                          for i in insp.get_indexes("invites")),
    }


def test_0004_marks_only_code_only_invites_reusable(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0003_lockdown")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            _insert_legacy_invite(conn, church_id, user_id, code="CODEONLY")
            _insert_legacy_invite(conn, church_id, user_id, code="PENDING", email="new@example.com")
            _insert_legacy_invite(conn, church_id, user_id, code="USED", email="old@example.com",
                                  accepted_at=T9_NOW)
        _alembic(sqlite_url, "upgrade", "head")
        with engine.connect() as conn:
            rows = conn.execute(sa.text(
                "SELECT code, reusable, accepted_by FROM invites ORDER BY code")).all()
    finally:
        engine.dispose()
    assert [(code, bool(reusable), accepted_by) for code, reusable, accepted_by in rows] == [
        ("CODEONLY", True, None),
        ("PENDING", False, None),
        ("USED", False, None),
    ]


def test_0004_downgrade_drops_the_columns_and_fk(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0003_lockdown")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            before = _invites_shape(conn)
        _alembic(sqlite_url, "upgrade", "head")
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            _insert_legacy_invite(conn, church_id, user_id, code="KEEP")
            at_head = _invites_shape(conn)
        _alembic(sqlite_url, "downgrade", "0003_lockdown")
        with engine.connect() as conn:
            after = _invites_shape(conn)
            codes = conn.execute(sa.text("SELECT code FROM invites")).scalars().all()
            version = conn.execute(sa.text("SELECT version_num FROM alembic_version")).scalar_one()
    finally:
        engine.dispose()
    assert at_head["columns"] == before["columns"] + [
        ("reusable", "BOOLEAN", False), ("accepted_by", "CHAR(32)", True)]
    assert at_head["fks"] == sorted(before["fks"] + [
        ("fk_invites_accepted_by_users", ("accepted_by",), "users", ("id",), "SET NULL")])
    assert after == before          # the recreate kept every other column, key and index
    assert codes == ["KEEP"]        # and the rows
    assert version == "0003_lockdown"


def test_an_insert_without_reusable_gets_false(sqlite_url):
    _alembic(sqlite_url, "upgrade", "head")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            _insert_legacy_invite(conn, church_id, user_id, code="STREAMLIT")
        with engine.connect() as conn:
            reusable, accepted_by = conn.execute(sa.text(
                "SELECT reusable, accepted_by FROM invites WHERE code = 'STREAMLIT'")).one()
    finally:
        engine.dispose()
    assert (bool(reusable), accepted_by) == (False, None)


# --- Slice 5a-2: 0005_services_extras (F §3.4, §3.5; 5a spec "Data and migrations") ---

# The services columns before 0005, i.e. everything a pre-5a-2 insert names
# (frozen Streamlit's ORM, migrate_to_db.py): never custom_elements or hymnal.
_legacy_services = sa.table(
    "services",
    sa.column("id", sa.Uuid()),
    sa.column("church_id", sa.Uuid()),
    sa.column("created_by", sa.Uuid()),
    sa.column("service_date_iso", sa.String()),
    sa.column("service_date_display", sa.String()),
    sa.column("occasion", sa.String()),
    sa.column("scriptures", sa.JSON()),
    sa.column("hymns", sa.JSON()),
    sa.column("liturgy", sa.JSON()),
    sa.column("sermon_title", sa.String()),
    sa.column("selected_ot_ref", sa.String()),
    sa.column("selected_nt_ref", sa.String()),
    sa.column("include_communion", sa.Boolean()),
    sa.column("saved_at", sa.DateTime(timezone=True)),
)

# What `alembic upgrade 0004_invites_reusable:0005_services_extras --sql` prints
# on Postgres, comments and blank lines left out: the preview the owner reads
# before the merge (5a-2 plan, owner answer 8; backend/migrations/README.md).
PREVIEW_0005 = [
    "BEGIN;",
    "SET LOCAL lock_timeout = '5s';",
    "SET LOCAL statement_timeout = '60s';",
    "ALTER TABLE services ADD COLUMN custom_elements JSON;",
    "ALTER TABLE services ADD COLUMN hymnal VARCHAR;",
    "CREATE INDEX ix_services_church_date ON services (church_id, service_date_iso);",
    "UPDATE alembic_version SET version_num='0005_services_extras' "
    "WHERE alembic_version.version_num = '0004_invites_reusable';",
    "COMMIT;",
]


def _insert_legacy_service(conn, church_id, user_id, *, date_iso="2026-09-27") -> uuid.UUID:
    service_id = uuid.uuid4()
    conn.execute(_legacy_services.insert().values(
        id=service_id, church_id=church_id, created_by=user_id, service_date_iso=date_iso,
        service_date_display="September 27, 2026", occasion="Pentecost 17", scriptures=["Psalm 25"],
        hymns=[{"title": "Holy, Holy, Holy", "number": 138}], liturgy={"call_to_worship": "Come."},
        sermon_title="", selected_ot_ref="", selected_nt_ref="", include_communion=False, saved_at=T9_NOW))
    return service_id


def _services_shape(conn) -> dict:
    insp = sa.inspect(conn)
    return {
        "columns": [(c["name"], str(c["type"]), c["nullable"]) for c in insp.get_columns("services")],
        "pk": insp.get_pk_constraint("services")["constrained_columns"],
        "fks": sorted((fk["name"] or "", tuple(fk["constrained_columns"]), fk["referred_table"],
                       fk["options"].get("ondelete")) for fk in insp.get_foreign_keys("services")),
        "indexes": sorted((i["name"], tuple(i["column_names"]), bool(i["unique"]))
                          for i in insp.get_indexes("services")),
    }


def test_0005_adds_two_nullable_columns_and_the_date_index_and_keeps_rows(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0004_invites_reusable")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            kept = _insert_legacy_service(conn, church_id, user_id)
            before = _services_shape(conn)
        _alembic(sqlite_url, "upgrade", "0005_services_extras")
        with engine.begin() as conn:
            at_head = _services_shape(conn)
            inserted = _insert_legacy_service(conn, church_id, user_id, date_iso="2026-10-04")
            rows = conn.execute(sa.text(
                "SELECT id, occasion, custom_elements, hymnal FROM services ORDER BY service_date_iso")).all()
    finally:
        engine.dispose()
    assert at_head["columns"] == before["columns"] + [
        ("custom_elements", "JSON", True), ("hymnal", "VARCHAR", True)]
    assert at_head["indexes"] == sorted(before["indexes"] + [
        ("ix_services_church_date", ("church_id", "service_date_iso"), False)])
    assert (at_head["pk"], at_head["fks"]) == (before["pk"], before["fks"])
    # The row from before keeps its data; an insert that names neither column gets NULLs.
    assert [(uuid.UUID(str(r.id)), r.occasion, r.custom_elements, r.hymnal) for r in rows] == [
        (kept, "Pentecost 17", None, None), (inserted, "Pentecost 17", None, None)]


def test_0005_downgrade_gives_back_the_0004_services_table(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0004_invites_reusable")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            before = _services_shape(conn)
        _alembic(sqlite_url, "upgrade", "head")
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            _insert_legacy_service(conn, church_id, user_id)
            conn.execute(sa.text("UPDATE services SET custom_elements = '[]', hymnal = 'GG2013'"))
        _alembic(sqlite_url, "downgrade", "0004_invites_reusable")
        with engine.connect() as conn:
            after = _services_shape(conn)
            occasions = conn.execute(sa.text("SELECT occasion FROM services")).scalars().all()
            version = conn.execute(sa.text("SELECT version_num FROM alembic_version")).scalar_one()
    finally:
        engine.dispose()
    assert after == before          # the table copy kept every other column, key and index
    assert occasions == ["Pentecost 17"]
    assert version == "0004_invites_reusable"


def test_offline_sql_for_0005_is_two_column_adds_and_one_index_under_the_timeouts():
    cfg = alembic_config(url="postgresql://preview@localhost:1/preview", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "0004_invites_reusable:0005_services_extras", sql=True)
    lines = [line for line in buffer.getvalue().splitlines() if line.strip() and not line.startswith("--")]
    assert lines == PREVIEW_0005


def test_the_readme_shows_the_0005_preview_exactly():
    """The owner reads backend/migrations/README.md → "Before 0005_services_extras",
    step 3, against the agent's rendering; both must be PREVIEW_0005."""
    readme = (Path(__file__).resolve().parents[1] / "migrations" / "README.md").read_text(encoding="utf-8")
    section = readme.split("\n## Before 0005_services_extras (slice 5a-2)\n", 1)[1]
    step = section.split("\n### Step 3: Read the SQL the upgrade will run\n", 1)[1].split("\n### ", 1)[0]
    block = "BEGIN;" + step.split("\n```\nBEGIN;", 1)[1].split("\n```", 1)[0]   # the bare fence
    assert block.splitlines() == PREVIEW_0005


# --- Printed bulletin PR 2b: 0006_services_bulletin (F §3.4, §3.5; printed bulletin spec "Data model") ---

# What `alembic upgrade 0005_services_extras:0006_services_bulletin --sql` prints on
# Postgres, comments and blank lines left out: the preview the owner reads before
# the merge (PR 2 planning answer 8; backend/migrations/README.md).
PREVIEW_0006 = [
    "BEGIN;",
    "SET LOCAL lock_timeout = '5s';",
    "SET LOCAL statement_timeout = '60s';",
    "ALTER TABLE services ADD COLUMN bulletin JSON;",
    "UPDATE alembic_version SET version_num='0006_services_bulletin' "
    "WHERE alembic_version.version_num = '0005_services_extras';",
    "COMMIT;",
]


def test_0006_adds_the_nullable_bulletin_column_and_keeps_rows(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0005_services_extras")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            kept = _insert_legacy_service(conn, church_id, user_id)
            before = _services_shape(conn)
        _alembic(sqlite_url, "upgrade", "head")
        with engine.begin() as conn:
            at_head = _services_shape(conn)
            inserted = _insert_legacy_service(conn, church_id, user_id, date_iso="2026-10-04")
            rows = conn.execute(sa.text("SELECT id, occasion, bulletin FROM services ORDER BY service_date_iso")).all()
    finally:
        engine.dispose()
    assert at_head["columns"] == before["columns"] + [("bulletin", "JSON", True)]
    assert (at_head["pk"], at_head["fks"], at_head["indexes"]) == (before["pk"], before["fks"], before["indexes"])
    # The row from before keeps its data; an insert that does not name the column gets NULL.
    assert [(uuid.UUID(str(r.id)), r.occasion, r.bulletin) for r in rows] == [
        (kept, "Pentecost 17", None), (inserted, "Pentecost 17", None)]


def test_0006_downgrade_gives_back_the_0005_services_table(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0005_services_extras")
    engine = sa.create_engine(sqlite_url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            before = _services_shape(conn)
        _alembic(sqlite_url, "upgrade", "head")
        with engine.begin() as conn:
            user_id, church_id = _seed_owner_and_church(conn)
            _insert_legacy_service(conn, church_id, user_id)
            conn.execute(sa.text("""UPDATE services SET custom_elements = '[]', hymnal = 'GG2013',
                                    bulletin = '{"announcements": {"coffee_hour": "Sam Sample"}}'"""))
        _alembic(sqlite_url, "downgrade", "0005_services_extras")
        with engine.connect() as conn:
            after = _services_shape(conn)
            rows = conn.execute(sa.text("SELECT occasion, hymnal FROM services")).all()
            version = conn.execute(sa.text("SELECT version_num FROM alembic_version")).scalar_one()
    finally:
        engine.dispose()
    assert after == before          # the table copy kept every other column, key and index
    assert [tuple(r) for r in rows] == [("Pentecost 17", "GG2013")]
    assert version == "0005_services_extras"


def test_offline_sql_for_0006_is_one_column_add_under_the_timeouts():
    cfg = alembic_config(url="postgresql://preview@localhost:1/preview", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "0005_services_extras:0006_services_bulletin", sql=True)
    lines = [line for line in buffer.getvalue().splitlines() if line.strip() and not line.startswith("--")]
    assert lines == PREVIEW_0006


def test_the_readme_shows_the_0006_preview_exactly():
    """The owner reads backend/migrations/README.md → "Before 0006_services_bulletin",
    step 3, against the agent's rendering; both must be PREVIEW_0006."""
    readme = (Path(__file__).resolve().parents[1] / "migrations" / "README.md").read_text(encoding="utf-8")
    section = readme.split("\n## Before 0006_services_bulletin (printed bulletin PR 2b-1)\n", 1)[1]
    step = section.split("\n### Step 3: Read the SQL the upgrade will run\n", 1)[1].split("\n### ", 1)[0]
    block = "BEGIN;" + step.split("\n```\nBEGIN;", 1)[1].split("\n```", 1)[0]   # the bare fence
    assert block.splitlines() == PREVIEW_0006
