"""Alembic migrations: env.py, the revisions, offline SQL (F §3.1-§3.3; slice 1 spec)."""
import io
import logging.config
from contextlib import contextmanager
from pathlib import Path

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import CheckConstraint, Integer, create_engine, inspect
from sqlalchemy.pool import NullPool

from db import models  # noqa: F401  (registers every table on Base.metadata)
from db.engine import Base
from db.schema_check import ALEMBIC_INI, alembic_config, schema_diff


def _alembic(url: str, *args, **kw):
    """Run one Alembic command in-process on `url`; never reads DATABASE_URL, never touches logging."""
    return getattr(command, args[0])(alembic_config(url=url, configure_logger=False), *args[1:], **kw)


@pytest.fixture
def sqlite_url(tmp_path):
    return f"sqlite:///{tmp_path / 'migrations.db'}"


# --- env.py -------------------------------------------------------------------

@pytest.mark.parametrize("configure_logger", [True, False])
def test_env_py_configures_logging_only_when_asked(monkeypatch, sqlite_url, configure_logger):
    calls = []
    monkeypatch.setattr(logging.config, "fileConfig", lambda *a, **kw: calls.append((a, kw)))
    command.current(alembic_config(url=sqlite_url, configure_logger=configure_logger))
    expected = [((str(ALEMBIC_INI),), {"disable_existing_loggers": False})] if configure_logger else []
    assert calls == expected


def test_env_py_uses_the_configured_url_not_database_url(monkeypatch, capsys, sqlite_url, tmp_path):
    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@pooler.invalid:5432/postgres")
    _alembic(sqlite_url, "current")
    err = capsys.readouterr().err
    assert "Database: dialect=sqlite" in err
    assert "pooler.invalid" not in err
    assert (tmp_path / "migrations.db").exists()


def test_env_py_prints_the_database_line_to_stderr_only(capsys, sqlite_url, tmp_path):
    _alembic(sqlite_url, "current")
    out, err = capsys.readouterr()
    assert f"Database: dialect=sqlite driver=pysqlite host=- database={tmp_path / 'migrations.db'}\n" in err
    assert "Database:" not in out


# --- 0001_baseline (Task 6) ------------------------------------------------------

BASELINE_TABLES = {
    "users", "churches", "memberships", "invites", "hymn_catalog", "hymns",
    "services", "hymn_usage", "contacts", "gmail_tokens", "oauth_states",
}


def _script() -> ScriptDirectory:
    return ScriptDirectory.from_config(alembic_config(configure_logger=False))


@contextmanager
def _connection(url: str):
    """A short-lived connection of its own (NullPool), closed and disposed on exit."""
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            yield conn
    finally:
        engine.dispose()


def test_upgrade_head_on_empty_sqlite_matches_the_models(sqlite_url):
    _alembic(sqlite_url, "upgrade", "head")
    with _connection(sqlite_url) as conn:
        assert schema_diff(conn) == []
    _alembic(sqlite_url, "check")   # AC1: raises AutogenerateDiffsDetected on any difference


def test_downgrade_base_then_upgrade_head(sqlite_url):
    _alembic(sqlite_url, "upgrade", "head")
    _alembic(sqlite_url, "downgrade", "base")
    with _connection(sqlite_url) as conn:
        assert inspect(conn).get_table_names() == ["alembic_version"]
        assert conn.exec_driver_sql("SELECT count(*) FROM alembic_version").scalar() == 0
    _alembic(sqlite_url, "upgrade", "head")
    with _connection(sqlite_url) as conn:
        assert schema_diff(conn) == []
        versions = conn.exec_driver_sql("SELECT version_num FROM alembic_version").scalars().all()
    assert versions == [_script().get_current_head()]


def test_every_revision_defines_downgrade():
    revisions = list(_script().walk_revisions())
    assert revisions
    for rev in revisions:
        assert callable(getattr(rev.module, "downgrade", None)), rev.revision
        assert Path(rev.path).name == f"{rev.revision}.py"   # NNNN_short_slug.py, id = file name


def test_there_is_a_single_head():
    script = _script()
    assert len(script.get_heads()) == 1
    assert script.get_bases() == ["0001_baseline"]
    assert not [rev.revision for rev in script.walk_revisions()
                if rev.is_branch_point or rev.is_merge_point]


def test_baseline_creates_the_eleven_tables_with_hymn_facts_columns(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0001_baseline")
    with _connection(sqlite_url) as conn:
        insp = inspect(conn)
        assert set(insp.get_table_names()) == BASELINE_TABLES | {"alembic_version"}
        for table in ("hymns", "hymn_catalog"):
            columns = {column["name"]: column for column in insp.get_columns(table)}
            for name in ("text_year", "hymnal_count"):
                assert isinstance(columns[name]["type"], Integer), (table, name)
                assert columns[name]["nullable"] is True, (table, name)
        assert {ix["name"]: ix["column_names"] for ix in insp.get_indexes("hymns")} == {
            "ix_hymns_church_id": ["church_id"],
            "ix_hymns_church_hymnal": ["church_id", "hymnal"],
            "ix_hymns_church_number": ["church_id", "number"],
        }


def _on_delete_rules_in_the_models() -> dict:
    return {
        (table.name, tuple(fk.column_keys), fk.referred_table.name): (fk.ondelete or "").upper() or None
        for table in Base.metadata.sorted_tables
        for fk in table.foreign_key_constraints
    }


def _check_constraints_in_the_models() -> dict:
    return {
        table.name: sorted((c.name, str(c.sqltext)) for c in table.constraints
                           if isinstance(c, CheckConstraint))
        for table in Base.metadata.sorted_tables
    }


def test_baseline_keeps_on_delete_rules_and_check_constraints(sqlite_url):
    """ON DELETE rules and CHECK constraints equal the models' after `upgrade head`.

    Autogenerate never compares CHECK constraints, and whether it compares ON
    DELETE depends on the Alembic version and the dialect, so schema_diff alone
    cannot be trusted with either. Runs at head, so it keeps holding when a later
    revision rebuilds a table (0004's batch mode on SQLite)."""
    _alembic(sqlite_url, "upgrade", "head")
    expected_rules = _on_delete_rules_in_the_models()
    expected_checks = _check_constraints_in_the_models()
    assert expected_rules[("memberships", ("church_id",), "churches")] == "CASCADE"
    assert expected_rules[("services", ("created_by",), "users")] == "SET NULL"
    assert expected_checks["memberships"] == [("ck_memberships_role", "role IN ('owner','admin','member')")]
    with _connection(sqlite_url) as conn:
        insp = inspect(conn)
        rules = {
            (table, tuple(fk["constrained_columns"]), fk["referred_table"]):
                (fk["options"].get("ondelete") or "").upper() or None
            for table in Base.metadata.tables
            for fk in insp.get_foreign_keys(table)
        }
        checks = {
            table: sorted((c["name"], c["sqltext"]) for c in insp.get_check_constraints(table))
            for table in Base.metadata.tables
        }
    assert rules == expected_rules
    assert checks == expected_checks


def test_offline_sql_wraps_timeouts_in_one_transaction(capsys):
    """`upgrade --sql` on Postgres opens no connection (port 1 has no server)."""
    cfg = alembic_config(url="postgresql://u:p@localhost:1/x", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "head", sql=True)
    sql = buffer.getvalue()
    lines = [line for line in sql.splitlines() if line.strip() and not line.startswith("--")]
    assert lines[:3] == ["BEGIN;", "SET LOCAL lock_timeout = '5s';", "SET LOCAL statement_timeout = '60s';"]
    assert lines[-1] == "COMMIT;"
    assert sql.count("BEGIN;") == 1
    assert sql.count("COMMIT;") == 1
    assert "CREATE TABLE users (" in sql
    assert "Database:" not in sql
    assert "Database: dialect=postgresql driver=psycopg2 host=localhost database=x" in capsys.readouterr().err


# --- Task 7: 0002_reconcile (F §3.2 item 3; S amendment 2026-09-26; AC18) ------
import io

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.pool import NullPool

from db.schema_check import schema_diff

RECONCILE_TABLES = ("hymns", "hymn_catalog")
RECONCILE_COLUMNS = ("text_year", "hymnal_count")


def _execute_on(url: str, *statements: str) -> None:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as conn:
            for statement in statements:
                conn.execute(text(statement))
    finally:
        engine.dispose()


def _legacy_database(url: str, *, without_hymn_facts: bool = False,
                     without_hymnal_index: bool = False) -> None:
    """A database the old create_all made (no alembic_version table): the 0001
    schema, minus what an older one lacked (PR #4's columns, or the index
    migrate_add_hymnal.py never created)."""
    _alembic(url, "upgrade", "0001_baseline")
    statements = ["DROP TABLE alembic_version"]
    if without_hymnal_index:
        statements.append("DROP INDEX ix_hymns_church_hymnal")
    if without_hymn_facts:
        statements += [f"ALTER TABLE {table} DROP COLUMN {column}"
                       for table in RECONCILE_TABLES for column in RECONCILE_COLUMNS]
    _execute_on(url, *statements)


def _tables_snapshot(url: str) -> dict:
    """{table: (sorted (column, type, nullable), sorted (index, columns))}."""
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            insp = inspect(conn)
            return {
                table: (
                    sorted((c["name"], str(c["type"]), c["nullable"]) for c in insp.get_columns(table)),
                    sorted((i["name"], tuple(i["column_names"])) for i in insp.get_indexes(table)),
                )
                for table in insp.get_table_names()
            }
    finally:
        engine.dispose()


def _snapshot_columns(snapshot: dict, table: str) -> set[str]:
    return {name for name, _type, _nullable in snapshot[table][0]}


def _models_diff(url: str) -> list:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            return schema_diff(conn)
    finally:
        engine.dispose()


def test_a_pre_pr4_database_stamped_at_baseline_gains_hymn_facts(sqlite_url):
    _legacy_database(sqlite_url, without_hymn_facts=True)
    before = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:
        assert not set(RECONCILE_COLUMNS) & _snapshot_columns(before, table)

    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")

    after = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:
        columns = {name: (type_, nullable) for name, type_, nullable in after[table][0]}
        assert columns["text_year"] == ("INTEGER", True)
        assert columns["hymnal_count"] == ("INTEGER", True)
    assert _models_diff(sqlite_url) == []


def test_upgrade_head_twice_changes_nothing(sqlite_url):
    _legacy_database(sqlite_url, without_hymn_facts=True, without_hymnal_index=True)
    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")
    first = _tables_snapshot(sqlite_url)

    _alembic(sqlite_url, "upgrade", "head")              # already at head: nothing runs
    assert _tables_snapshot(sqlite_url) == first

    # 0002 itself a second time, as on production, which already has everything.
    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "0002_reconcile")
    assert _tables_snapshot(sqlite_url) == first


def test_on_a_fresh_database_0002_adds_nothing(sqlite_url):
    _alembic(sqlite_url, "upgrade", "0001_baseline")
    baseline = _tables_snapshot(sqlite_url)
    for table in RECONCILE_TABLES:                       # 0001 already made them
        assert set(RECONCILE_COLUMNS) <= _snapshot_columns(baseline, table)
    assert ("ix_hymns_church_hymnal", ("church_id", "hymnal")) in baseline["hymns"][1]

    _alembic(sqlite_url, "upgrade", "0002_reconcile")

    assert _tables_snapshot(sqlite_url) == baseline


def test_a_stamped_database_missing_the_hymnal_index_gets_it(sqlite_url):
    _legacy_database(sqlite_url, without_hymnal_index=True)
    assert "ix_hymns_church_hymnal" not in {name for name, _cols in _tables_snapshot(sqlite_url)["hymns"][1]}

    _alembic(sqlite_url, "stamp", "0001_baseline")
    _alembic(sqlite_url, "upgrade", "head")

    assert ("ix_hymns_church_hymnal", ("church_id", "hymnal")) in _tables_snapshot(sqlite_url)["hymns"][1]
    assert _models_diff(sqlite_url) == []


def test_offline_sql_from_baseline_renders_guarded_adds_and_no_create_table():
    # Runbook step 5: `alembic upgrade 0001_baseline:head --sql`. Offline mode
    # never connects (port 1 on localhost would refuse anyway).
    cfg = alembic_config(url="postgresql://u:p@localhost:1/x", configure_logger=False)
    cfg.output_buffer = buffer = io.StringIO()
    command.upgrade(cfg, "0001_baseline:head", sql=True)
    sql = buffer.getvalue()

    assert "CREATE TABLE" not in sql
    assert "CREATE INDEX IF NOT EXISTS ix_hymns_church_hymnal ON hymns (church_id, hymnal);" in sql
    for table in RECONCILE_TABLES:
        for column in RECONCILE_COLUMNS:
            assert f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} INTEGER;" in sql
    assert sql.count("ADD COLUMN IF NOT EXISTS") == 4
    assert ("UPDATE alembic_version SET version_num='0002_reconcile' "
            "WHERE alembic_version.version_num = '0001_baseline';") in sql
